name: BradMcGonigle
favicon: null
layout_spectrum: 0.47985
typography_spectrum: 0.82892
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#300D04'
    - '#89BCF0'
    - '#FABC88'
    - '#F2FAFF'
    - '#77775C'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
